version: '3'
services:
  api:
    build: ../emergencies-api
    ports:
     - "3000"
    env_file: ./config/dev/dev.env
    networks:
     - backend
  redis:
    image: "redis:alpine"
    ports:
     - "6379"
    networks:
     - backend
  postgres:
    image: "postgres:10"
    env_file: ./config/dev/dev.env
    ports:
     - "5432"
    networks:
     - backend
  nginx:
    build: ./nginx
    ports:
     - "80:80"
    image: "emergencies:nginx"
    networks:
     - backend
     - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
